apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
    nodePort: 30001  # This is the port you will use to access MLflow
