apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app
        image: us-west2-docker.pkg.dev/msds-ml-ops-25/reddit-app/reddit-app:latest
        ports:
        - containerPort: 5050
        command: ["uvicorn", "redditApp:app", "--host", "0.0.0.0", "--port", "5050"]
